Task - 2: Apply algorithm on digits dataset - One Hot Encoding of features: and Train test Division 65%-35%

In [ ]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

#Load dataset
digits = datasets.load_digits()
print(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [ ]:
print(digits.data.shape)
print(digits.target.shape)

(1797, 64)
(1797,)


In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split

X=digits.data
Y=digits.target

#split data set into train and test sets
X_train, X_test, y_train, y_test = train_test_split( 
    X, Y, test_size = 0.35, random_state = 44)

In [ ]:
#Create a Decision Tree Classifier
clf_gini = DecisionTreeClassifier()

clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
# Predict the classes of test data
y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)

Predicted values:
[4 5 1 7 9 0 7 5 1 1 5 4 2 7 2 8 2 0 5 1 9 4 1 1 5 2 4 6 1 3 9 0 4 8 6 2 3
 7 8 4 0 5 7 1 8 3 2 7 6 4 9 1 2 3 9 0 4 9 4 1 2 2 8 6 8 3 1 3 3 5 8 8 0 1
 6 5 8 6 7 2 9 9 3 2 0 8 7 4 2 9 0 3 5 6 6 3 6 0 0 9 5 3 1 1 0 1 1 1 5 1 1
 8 2 5 3 2 8 9 2 1 5 6 3 0 1 9 9 1 4 5 4 3 8 4 2 5 5 6 1 3 7 9 8 0 3 1 0 7
 2 6 0 9 2 1 7 9 2 7 1 1 0 1 1 2 4 5 2 0 1 9 1 7 5 5 3 9 4 6 0 2 0 0 3 0 0
 6 6 6 5 7 0 4 2 0 9 1 3 5 3 5 2 1 3 7 8 7 9 5 4 7 6 6 8 9 6 2 5 2 1 6 1 6
 6 6 7 0 0 0 4 0 0 1 9 6 7 3 0 3 0 9 1 8 9 7 0 9 0 3 0 7 3 4 4 9 9 9 5 5 0
 0 5 0 5 6 5 6 8 0 9 8 4 5 5 6 4 4 3 4 5 0 0 5 5 6 7 0 1 5 6 0 6 6 3 5 9 4
 1 1 2 9 1 0 7 9 0 0 1 1 9 8 5 3 1 3 0 3 3 3 7 0 6 2 1 8 2 1 5 3 7 5 3 2 8
 0 4 3 7 6 8 4 3 8 5 1 7 4 4 4 6 4 6 2 2 6 8 7 5 5 3 5 7 5 5 3 8 3 6 2 9 3
 7 6 2 0 0 1 2 4 3 4 4 7 8 4 5 4 1 3 4 3 5 6 4 5 3 6 8 1 3 2 0 4 1 5 1 9 7
 9 9 2 0 7 4 6 0 6 9 2 4 5 1 8 4 6 7 5 3 5 1 9 4 8 4 5 1 8 7 6 9 8 3 8 9 6
 8 3 1 3 2 8 6 5 4 7 4 6 4 9 2 6 4 4 3 4 1 2 1 7 6 5 7 5 9 7 8 1 6 7 5 8 0
 3 8 5 

In [ ]:
# Model Accuracy
from sklearn import metrics
print("Confusion Matrix: ",
        metrics.confusion_matrix(y_test, y_pred))
print ("Accuracy : ",
    metrics.accuracy_score(y_test,y_pred)*100)
print("Report : ",
    metrics.classification_report(y_test, y_pred))

Confusion Matrix:  [[64  0  0  0  1  1  0  0  0  0]
 [ 0 62  0  1  1  0  1  0  6  2]
 [ 1  3 47  0  0  0  3  1  2  0]
 [ 0  2  1 55  0  1  0  0  2  2]
 [ 1  1  0  0 52  0  0  1  0  2]
 [ 0  0  0  1  1 64  1  1  0  0]
 [ 0  0  2  0  2  1 60  0  3  0]
 [ 0  2  2  1  2  0  0 45  2  1]
 [ 0  7  2  5  1  1  0  1 35  3]
 [ 4  1  0  3  3  3  0  1  2 50]]
Accuracy :  84.8966613672496
Report :                precision    recall  f1-score   support

           0       0.91      0.97      0.94        66
           1       0.79      0.85      0.82        73
           2       0.87      0.82      0.85        57
           3       0.83      0.87      0.85        63
           4       0.83      0.91      0.87        57
           5       0.90      0.94      0.92        68
           6       0.92      0.88      0.90        68
           7       0.90      0.82      0.86        55
           8       0.67      0.64      0.65        55
           9       0.83      0.75      0.79        67

    accuracy   